[project]
name = "paddleocr-docker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "paddleocr>=2.7.3",
    "paddlepaddle>=2.6.2",
    "ruff>=0.7.2",
    "setuptools>=75.3.0",
    "wheel>=0.44.0",
]
